version: '3.4'
services:
  db:
    image: mysql:8.0
    ports:
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_INITDB_ARGS=--encoding=UTF-8
      - TZ=UTC
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: 'mysqladmin ping -h localhost -u ${DB_USER_NAME} --password=${DB_USER_PASSWORD}'
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 0s
    volumes:
      - ./data/db:/var/lib/mysql
  api:
    image: rookies-inpyeon-backend
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PHASE=${PHASE}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CALLBACK_URL=${KAKAO_CALLBACK_URL}
      - FRONT_URL=${FRONT_URL}
      - ORIGIN_LIST=${ORIGIN_LIST}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
